git config --global alias.l  "log --oneline --graph"
git config --global alias.la  "l --all"
git config --global alias.ps  "push"
git config --global alias.fps  "ps --force-with-lease"
git config --global alias.pl  "pull"
git config --global alias.f  "fetch -p"
git config --global alias.s  "status -u"
git config --global alias.d  "diff"
git config --global alias.dc  "d --cached"
git config --global alias.c  "commit"
git config --global alias.ca  "c -a"
git config --global alias.cm  "c --amend"
git config --global alias.smu "submodule update --init --recursive"
git config --global alias.b "branch"
git config --global alias.ba "branch -a"
git config --global alias.ch "checkout --recurse-submodules"
git config --global alias.chn "checkout -b"
git config --global alias.a "add"
git config --global alias.aa "a ."
git config --global alias.ap "a -p"
git config --global alias.ro "restore"
git config --global alias.ros "ro --staged"
git config --global alias.rb "rebase"
git config --global alias.rbc "rb --continue"
git config --global alias.rbi "rb -i"
git config --global alias.mg "merge"
git config --global alias.mgc "mg --continue"
git config --global alias.ff "mg --ff-only"
git config --global alias.sh "show --name-status"
git config --global alias.conf "config --global --edit"
git config --global alias.lconf "config --local --edit"
git config --global alias.renorm "add --renormalize ."
git config --global alias.fix "c --fixup"
git config --global alias.autosquash  "rbi --autosquash"
git config --global alias.assume-unchanged "update-index --assume-unchanged"